command_name: "3"
attributes:
  - name: current_temperature
    id: "0"
  - name: mode
    id: "5"
    mappings:
      - haier: 0
        value: auto
      - haier: 1
        value: cool
      - haier: 2
        value: dry
      - haier: 4
        value: heat
      - haier: 6
        value: fan_only
  - name: fan_mode
    id: "6"
    mappings:
      - haier: 1
        value: high
      - haier: 2
        value: medium
      - haier: 3
        value: low
      - haier: 5
        value: auto
  - name: status
    id: "21"
  - name: target_temperature
    id: "31"